{'videoId': 'Io_gdSvyjjk',
 'thumbnail': {'thumbnails': [{'url': 'https://i.ytimg.com/vi/Io_gdSvyjjk/hqdefault.jpg?sqp=-oaymwE1CKgBEF5IVfKriqkDKAgBFQAAiEIYAXABwAEG8AEB-AH-CYAC0AWKAgwIABABGHIgVSg9MA8=&rs=AOn4CLCZdYkns9TIazaYBjiIovTGi3nMgw', 'width': 168, 'height': 94},
                                                        {'url': 'https://i.ytimg.com/vi/Io_gdSvyjjk/hqdefault.jpg?sqp=-oaymwE1CMQBEG5IVfKriqkDKAgBFQAAiEIYAXABwAEG8AEB-AH-CYAC0AWKAgwIABABGHIgVSg9MA8=&rs=AOn4CLBrL0qTQjL9Lt6SOkJU2idQCrOG-A', 'width': 196, 'height': 110},
                                                        {'url': 'https://i.ytimg.com/vi/Io_gdSvyjjk/hqdefault.jpg?sqp=-oaymwE2CPYBEIoBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_gmAAtAFigIMCAAQARhyIFUoPTAP&rs=AOn4CLDcB0A9QghSyNmt-5q0fVC_r3xhIA', 'width': 246, 'height': 138},
                                                        {'url': 'https://i.ytimg.com/vi/Io_gdSvyjjk/hqdefault.jpg?sqp=-oaymwE2CNACELwBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_gmAAtAFigIMCAAQARhyIFUoPTAP&rs=AOn4CLAwlELczUpp0IEYOQHapgmMu6S7XQ', 'width': 336, 'height': 188}]},
 'title': {'runs': [{'text': 'President Obama Celebrates a Construction Milestone'}],
           'accessibility': {'accessibilityData': {'label': 'President Obama Celebrates a Construction Milestone by Obama Foundation 10,787 views 11 days ago 2 minutes, 24 seconds'}}},
 'descriptionSnippet': {'runs': [{'text': 'President Obama visited the Obama Presidential Center construction site in Chicago to celebrate a significant milestone: the Museum Building, the tallest structure on the 19.3-acre campus,...'}]},
 'publishedTimeText': {'simpleText': '11 days ago'},
 'lengthText': {'accessibility': {'accessibilityData': {'label': '2 minutes, 24 seconds'}}, 'simplfeText': '2:24'},
 'viewCountText': {'simpleText': '10,787 views'},
 'navigationEndpoint': {'clickTrackingParams': 'CPMBENwwIhMI-9Oau6jzhgMVp14PAh01cwZuWhhVQ2lhYmEtRG1ZSmFjcGhqN3I3S25yd2eaAQMQ8jg=',
                        'commandMetadata': {'webCommandMetadata': {'url': '/watch?v=Io_gdSvyjjk', 'webPageType': 'WEB_PAGE_TYPE_WATCH', 'rootVe': 3832}},
                        'watchEndpoint': {'videoId': 'Io_gdSvyjjk',
                                          'watchEndpointSupportedOnesieConfig': {'html5PlaybackOnesieConfig': {'commonConfig': {'url': 'https://rr5---sn-i3belnl7.googlevideo.com/initplayback?source=youtube&oeis=1&c=WEB&oad=3200&ovd=3200&oaad=11000&oavd=11000&ocs=700&oewis=1&oputc=1&ofpcc=1&msp=1&odepv=1&id=228fe0752bf28e39&ip=50.114.59.25&initcwndbps=6485000&mt=1719199983&oweuc='}}}}},
 'ownerBadges': [{'metadataBadgeRenderer': {'icon': {'iconType': 'CHECK_CIRCLE_THICK'}, 'style': 'BADGE_STYLE_TYPE_VERIFIED', 'tooltip': 'Verified', 'trackingParams': 'CPMBENwwIhMI-9Oau6jzhgMVp14PAh01cwZu', 'accessibilityData': {'label': 'Verified'}}}],
 'trackingParams': 'CPMBENwwIhMI-9Oau6jzhgMVp14PAh01cwZuQLmcyt_SjvjHIg==',
 'showActionMenu': False,
 'shortViewCountText': {'accessibility': {'accessibilityData': {'label': '10K views'}}, 'simpleText': '10K views'},
 'menu': {'menuRenderer': {'items': [{'menuServiceItemRenderer': {'text': {'runs': [{'text': 'Add to queue'}]},
                                                                  'icon': {'iconType': 'ADD_TO_QUEUE_TAIL'},
                                                                  'serviceEndpoint': {'clickTrackingParams': 'CPgBEP6YBBgHIhMI-9Oau6jzhgMVp14PAh01cwZu',
                                                                                      'commandMetadata': {'webCommandMetadata': {'sendPost': True}},
                                                                                      'signalServiceEndpoint': {'signal': 'CLIENT_SIGNAL', 'actions': [{'clickTrackingParams': 'CPgBEP6YBBgHIhMI-9Oau6jzhgMVp14PAh01cwZu',
                                                                                                                                                        'addToPlaylistCommand': {'openMiniplayer': True, 'videoId': 'Io_gdSvyjjk',
                                                                                                                                                                                 'listType': 'PLAYLIST_EDIT_LIST_TYPE_QUEUE',
                                                                                                                                                                                 'onCreateListCommand': {'clickTrackingParams': 'CPgBEP6YBBgHIhMI-9Oau6jzhgMVp14PAh01cwZu',
                                                                                                                                                                                                         'commandMetadata': {'webCommandMetadata': {'sendPost': True,
                                                                                                                                                                                                                                                    'apiUrl': '/youtubei/v1/playlist/create'}},
                                                                                                                                                                                                         'createPlaylistServiceEndpoint': {'videoIds': ['Io_gdSvyjjk'],
                                                                                                                                                                                                                                           'params': 'CAQ%3D'}},
                                                                                                                                                                                 'videoIds': ['Io_gdSvyjjk']}}]}},
                                                                  'trackingParams': 'CPgBEP6YBBgHIhMI-9Oau6jzhgMVp14PAh01cwZu'}},
                                     {'menuServiceItemDownloadRenderer': {'serviceEndpoint': {'clickTrackingParams': 'CPcBENGqBRgIIhMI-9Oau6jzhgMVp14PAh01cwZu', 'offlineVideoEndpoint': {'videoId': 'Io_gdSvyjjk', 'onAddCommand': {'clickTrackingParams': 'CPcBENGqBRgIIhMI-9Oau6jzhgMVp14PAh01cwZu', 'getDownloadActionCommand': {'videoId': 'Io_gdSvyjjk', 'params': 'CAIQAA%3D%3D'}}}},
                                                                          'trackingParams': 'CPcBENGqBRgIIhMI-9Oau6jzhgMVp14PAh01cwZu'}},
                                     {'menuServiceItemRenderer': {'text': {'runs': [{'text': 'Share'}]},
                                                                  'icon': {'iconType': 'SHARE'}, 'serviceEndpoint': {'clickTrackingParams': 'CPMBENwwIhMI-9Oau6jzhgMVp14PAh01cwZu', 'commandMetadata': {'webCommandMetadata': {'sendPost': True, 'apiUrl': '/youtubei/v1/share/get_share_panel'}},
                                                                                                                     'shareEntityServiceEndpoint': {'serializedShareEntity': 'CgtJb19nZFN2eWpqaw%3D%3D',
                                                                                                                                                    'commands': [{'clickTrackingParams': 'CPMBENwwIhMI-9Oau6jzhgMVp14PAh01cwZu',
                                                                                                                                                                  'openPopupAction': {'popup': {'unifiedSharePanelRenderer': {'trackingParams': 'CPYBEI5iIhMI-9Oau6jzhgMVp14PAh01cwZu', 'showLoadingSpinner': True}},
                                                                                                                                                                                      'popupType': 'DIALOG', 'beReused': True}}]}},
                                                                  'trackingParams': 'CPMBENwwIhMI-9Oau6jzhgMVp14PAh01cwZu'}}],
                           'trackingParams': 'CPMBENwwIhMI-9Oau6jzhgMVp14PAh01cwZu', 'accessibility': {'accessibilityData': {'label': 'Action menu'}}}},
 'thumbnailOverlays': [{'thumbnailOverlayTimeStatusRenderer': {'text': {'accessibility': {'accessibilityData': {'label': '2 minutes, 24 seconds'}}, 'simpleText': '2:24'}, 'style': 'DEFAULT'}},
                       {'thumbnailOverlayToggleButtonRenderer': {'isToggled': False, 'untoggledIcon': {'iconType': 'WATCH_LATER'},
                                                                 'toggledIcon': {'iconType': 'CHECK'},
                                                                 'untoggledTooltip': 'Watch later',
                                                                 'toggledTooltip': 'Added',
                                                                 'untoggledServiceEndpoint': {'clickTrackingParams': 'CPUBEPnnAxgCIhMI-9Oau6jzhgMVp14PAh01cwZu',
                                                                                              'commandMetadata': {'webCommandMetadata': {'sendPost': True, 'apiUrl': '/youtubei/v1/browse/edit_playlist'}},
                                                                                              'playlistEditEndpoint': {'playlistId': 'WL', 'actions': [{'addedVideoId': 'Io_gdSvyjjk', 'action': 'ACTION_ADD_VIDEO'}]}},
                                                                 'toggledServiceEndpoint': {'clickTrackingParams': 'CPUBEPnnAxgCIhMI-9Oau6jzhgMVp14PAh01cwZu',
                                                                                            'commandMetadata': {'webCommandMetadata': {'sendPost': True, 'apiUrl': '/youtubei/v1/browse/edit_playlist'}},
                                                                                            'playlistEditEndpoint': {'playlistId': 'WL', 'actions': [{'action': 'ACTION_REMOVE_VIDEO_BY_VIDEO_ID', 'removedVideoId': 'Io_gdSvyjjk'}]}},
                                                                 'untoggledAccessibility': {'accessibilityData': {'label': 'Watch later'}},
                                                                 'toggledAccessibility': {'accessibilityData': {'label': 'Added'}},
                                                                 'trackingParams': 'CPUBEPnnAxgCIhMI-9Oau6jzhgMVp14PAh01cwZu'}},
                       {'thumbnailOverlayToggleButtonRenderer': {'untoggledIcon': {'iconType': 'ADD_TO_QUEUE_TAIL'},
                                                                 'toggledIcon': {'iconType': 'PLAYLIST_ADD_CHECK'},
                                                                 'untoggledTooltip': 'Add to queue',
                                                                 'toggledTooltip': 'Added',
                                                                 'untoggledServiceEndpoint': {'clickTrackingParams': 'CPQBEMfsBBgDIhMI-9Oau6jzhgMVp14PAh01cwZu',
                                                                                              'commandMetadata': {'webCommandMetadata': {'sendPost': True}},
                                                                                              'signalServiceEndpoint': {'signal': 'CLIENT_SIGNAL', 'actions': [{'clickTrackingParams': 'CPQBEMfsBBgDIhMI-9Oau6jzhgMVp14PAh01cwZu',
                                                                                                                                                                'addToPlaylistCommand': {'openMiniplayer': True,
                                                                                                                                                                                         'videoId': 'Io_gdSvyjjk',
                                                                                                                                                                                         'listType': 'PLAYLIST_EDIT_LIST_TYPE_QUEUE',
                                                                                                                                                                                         'onCreateListCommand': {'clickTrackingParams': 'CPQBEMfsBBgDIhMI-9Oau6jzhgMVp14PAh01cwZu',
                                                                                                                                                                                                                 'commandMetadata': {'webCommandMetadata': {'sendPost': True, 'apiUrl': '/youtubei/v1/playlist/create'}},
                                                                                                                                                                                                                 'createPlaylistServiceEndpoint': {'videoIds': ['Io_gdSvyjjk'], 'params': 'CAQ%3D'}},
                                                                                                                                                                                         'videoIds': ['Io_gdSvyjjk']}}]}},
                                                                 'untoggledAccessibility': {'accessibilityData': {'label': 'Add to queue'}}, 'toggledAccessibility': {'accessibilityData': {'label': 'Added'}}, 'trackingParams': 'CPQBEMfsBBgDIhMI-9Oau6jzhgMVp14PAh01cwZu'}}, {'thumbnailOverlayNowPlayingRenderer': {'text': {'runs': [{'text': 'Now playing'}]}}}],
 'richThumbnail': {'movingThumbnailRenderer': {'movingThumbnailDetails': {'thumbnails': [{'url': 'https://i.ytimg.com/an_webp/Io_gdSvyjjk/mqdefault_6s.webp?du=3000&sqp=CJ_U47MG&rs=AOn4CLAhwslv-8_7Vb4UQr2t8R6ZhUGPkA', 'width': 320, 'height': 180}], 'logAsMovingThumbnail': True}, 'enableHoveredLogging': True, 'enableOverlay': True}}}
